### ISSUE TITLE
Periodic 409 HTTP responses

### ISSUE THREAD

**Issue by 88gts** [bachya/simplisafe-python#169]
**Describe the bug**
On latest version (and previous from that) I have been getting random failures when trying to poll for status.  Function below
```
async def main() -> None:
    """Create the aiohttp session and run the example."""
    async with ClientSession() as session:
        logging.basicConfig(level=logging.INFO)

        try:
            simplisafe = await API.login_via_credentials(
                SIMPLISAFE_EMAIL,
                SIMPLISAFE_PASSWORD,
                client_id=SIMPLISAFE_CLIENT_ID,
                session=session,
            )

            systems = await simplisafe.get_systems()
            for system in systems.values():
                await system.update(cached=False)
                _LOGGER.info('State: %s', system.state)
                        #"Sensor %s: (name: %s, type: %s, triggered:%s)",
                        #serial,
                        #sensor.name,
                        #sensor.type,
                        #sensor.triggered,
        except UnauthorizedError:
            _LOGGER.error("Invalid credentials")
        except SimplipyError as err:
            _LOGGER.error(err)

```

**To Reproduce**
Run simple script to get status

**Expected behavior**
Return status

```
Traceback (most recent call last):
  File "state.py", line 32, in main
    await system.update(cached=False)
  File "/var/www/scripts/simplisafe-python/simplipy/system/__init__.py", line 523, in update
    await self._get_entities(cached)
  File "/var/www/scripts/simplisafe-python/simplipy/system/__init__.py", line 290, in _get_entities
    entities: dict = await self._get_entities_payload(cached)
  File "/var/www/scripts/simplisafe-python/simplipy/system/v3.py", line 261, in _get_entities_payload
    params={"forceUpdate": str(not cached).lower()},
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 330, in request
    ) from None
simplipy.errors.RequestError: There was an error while requesting /ss3/subscriptions/2495324/sensors: 409, message='Conflict', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/2495324/sensors?forceUpdate=true')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "state.py", line 45, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "state.py", line 39, in main
    except UnauthorizedError:
NameError: name 'UnauthorizedError' is not defined
```

Rerunning the command tends to resolve the issue.

**Comment by bachya** [comment]
You're getting [an `HTTP 409` error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409), which can happen if you have multiple clients using this API at the same time.

**Comment by 88gts** [comment]
Hmm, I only have one client using this.  I'll keep an eye out.

**Comment by KTibow** [comment]
Stop notifying us bot, ask @88gts if it should be closed.

**Comment by 88gts** [comment]
I still see this, but my workaround is to run a loop when i issue the commands.  it is rare, and i never loop more than once or twice.  my issue itself is resolved, but there could be an issue in the code. based on my own logs, i see this ~10% of the time. i will close if im the only one seeing this though.

**Comment by bachya** [comment]
Thanks, @88gts. If you end up finding something that points to a code issue, feel free to comment here and we can reopen.
