### ISSUE TITLE
SimpliSafe websocket timeout every 900 seconds

### ISSUE THREAD

**Issue by slomanl1** [bachya/simplisafe-python#210]
I am receiving websocket timeout errors every 15 minutes. SimpliSafe server may not be sending the keep-alive messages or the API configuration has changed. I am running on Raspberry Pi4 4 GB. See  event log and configuration at below

**EVENT LOG**
```
2020-11-28** 20:42:29 INFO (MainThread) [socketio.client] Received event "confirm-registered" [/v1/user/1234567 ]
2020-11-28 20:50:13 INFO (MainThread) [socketio.client] Engine.IO connection dropped
2020-11-28 20:50:14 INFO (MainThread) [socketio.client] Engine.IO connection established
2020-11-28 20:50:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/engineio/asyncio_client.py", line 551, in _read_loop_websocket
    await self.write_loop_task
  File "/usr/local/lib/python3.8/site-packages/engineio/asyncio_client.py", line 622, in _write_loop
    await self.ws.send_str(pkt.encode(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2020-11-28 20:50:14 INFO (MainThread) [socketio.client] Namespace / is connected
2020-11-28 20:50:14 INFO (MainThread) [simplipy] Watchdog triggered – sleeping for 900 seconds
2020-11-28 20:50:14 INFO (MainThread) [homeassistant.components.simplisafe] Connected to websocket
2020-11-28 20:50:14 INFO (MainThread) [socketio.client] Namespace /v1/user/1234567 is connected
2020-11-28 20:50:14 INFO (MainThread) [socketio.client] Received event "confirm-registered" [/v1/user/1234567 ]
```
****Home Assistant Core Integration****
```
version: 0.118.4
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.127-v7l
arch: armv7l
timezone: America/Denver
```
Home Assistant Cloud
```
logged_in: true
subscription_expiration: December 11, 2020, 5:00 PM
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: true
google_enabled: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok
```
Hass.io
```
host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 57.8 GB
disk_used: 4.2 GB
healthy: true
supported: true
board: rpi4
supervisor_api: ok
version_api: ok
installed_addons: IDE (2.2.0), FTP (3.5.0), Home Assistant Google Drive Backup (0.102.0), Terminal & SSH (8.10.0), Node-RED (7.2.11)

**Comment by KTibow** [comment]
Mind using 3 backticks to format your stuff?

**Comment by slomanl1** [comment]
> Mind using 3 backticks to format your stuff?
Sorry, I do not know what you mean by bacticks. Could you please give me an example?

**Comment by KTibow** [comment]
Put 3 backticks on a line, like ` and then on the next line put your stuff and make a new line then put 3 backticks again. Put the language after the first couple of backticks to get formatting.
```yaml
host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 57.8 GB
disk_used: 4.2 GB
healthy: true
supported: true
board: rpi4
supervisor_api: ok
version_api: ok
installed_addons: IDE (2.2.0), FTP (3.5.0), Home Assistant Google Drive Backup (0.102.0), Terminal & SSH (8.10.0), Node-RED (7.2.11)
```

**Comment by bachya** [comment]
@slomanl1 Yours is the only report of this, so I don't think there's an issue API-wide.

The stacktrace indicates that your connection is being forcibly closed. Can you confirm how you have your Pi connected to the network? Has it been dropping offline? Is there any regularity to the frequency in this issue occurring?

**Comment by slomanl1** [comment]
AAron,
I agree with your assessment that the problem does not lie in the API.
SInce I am using HASSOS on a raspberry Pi and all other HASS components are
running without problems, that seems to point to a problem with the wrapper
code in Homeassistant improperly handling the websocket requests.
Furthermore, the timeout occurs regularly every 900 seconds since no
message from the API is EVER processed. I am going to run the test program
simplisafe-python provides to see if I can observe any errant behavior in
an environment outside of HASSOS. Is it possible that having my Raspberry
Pi connected to both WiFi and Ethernet could cause any problems? I have a
EERO router very close to the Rpi which provides both wired and WiFi
interfaces.
LS

**Comment by bachya** [comment]
@slomanl1 I'm not a Pi networking expert, unfortunately, but I can't imagine that two network interfaces are somehow causing the problem. I like your idea of running the example script; let me know how you get on.

**Comment by slomanl1** [comment]
Aaron,
Can I re-post this issue to home-assistant
<https://github.com/home-assistant>/core
<https://github.com/home-assistant/core> , or do you take care of that?
Thanks
LS

**Comment by bachya** [comment]
@slomanl1 I can’t transfer an issue to a different organization, so you will need to recreate it.

**Comment by bachya** [comment]
Closing due to inactivity.
