### ISSUE TITLE
401 at strange intervals

### ISSUE THREAD

**Issue by bachya** [bachya/simplisafe-python#25]
**Describe the bug**
Every now and again, it appears that `simplipy` erroneously holds onto an access token after it's expired. An example of this manifesting is via a Home Assistant log:

```
Log Details (ERROR)
Tue Nov 27 2018 05:14:08 GMT-0700 (Mountain Standard Time)

Update for alarm_control_panel.simplisafe fails
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/simplipy/api.py", line 168, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 853, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/usr/src/app/homeassistant/components/alarm_control_panel/simplisafe.py", line 127, in async_update
    await self._system.update()
  File "/config/deps/lib/python3.6/site-packages/simplipy/system.py", line 200, in update
    await self._update_location_info()
  File "/config/deps/lib/python3.6/site-packages/simplipy/system.py", line 89, in _update_location_info
    subscription_resp = await self.api.get_subscription_data()
  File "/config/deps/lib/python3.6/site-packages/simplipy/api.py", line 133, in get_subscription_data
    params={'activeOnly': 'true'})
  File "/config/deps/lib/python3.6/site-packages/simplipy/api.py", line 179, in request
    'Error requesting data from {0}: {1}'.format(endpoint, err))
simplipy.errors.RequestError: Error requesting data from users/428836/subscriptions: 401, message='Unauthorized'
```

Running calls again will cause a refresh token to be used, a new access token to be retreived, and function to continue as normal. This leads me to believe that we're not giving enough "time buffer" before expiring the access token.

**Comment by akail** [comment]
Even with upgrading to version 3.1.14 I am still having this issue.  Once it starts happening it never it continues until the server is completely restarted.
